/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAskDataRouteImport } from './routes/_shell.ask-data'
import { Route as ShellBerandaRouteImport } from './routes/_shell.beranda'
import { Route as ShellChatRouteImport } from './routes/_shell.chat'
import { Route as ShellDataIndexRouteImport } from './routes/_shell.data.index'
import { Route as ShellDataDatasetIdRouteImport } from './routes/_shell.data.$datasetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAskDataRoute = ShellAskDataRouteImport.update({
  id: '/ask-data',
  path: '/ask-data',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBerandaRoute = ShellBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDataIndexRoute = ShellDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDataDatasetIdRoute = ShellDataDatasetIdRouteImport.update({
  id: '/data/$datasetId',
  path: '/data/$datasetId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-data': typeof ShellAskDataRoute
  '/beranda': typeof ShellBerandaRoute
  '/chat': typeof ShellChatRoute
  '/data/$datasetId': typeof ShellDataDatasetIdRoute
  '/data/': typeof ShellDataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-data': typeof ShellAskDataRoute
  '/beranda': typeof ShellBerandaRoute
  '/chat': typeof ShellChatRoute
  '/data/$datasetId': typeof ShellDataDatasetIdRoute
  '/data': typeof ShellDataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/ask-data': typeof ShellAskDataRoute
  '/_shell/beranda': typeof ShellBerandaRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/data/$datasetId': typeof ShellDataDatasetIdRoute
  '/_shell/data/': typeof ShellDataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ask-data' | '/beranda' | '/chat' | '/data/$datasetId' | '/data/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask-data' | '/beranda' | '/chat' | '/data/$datasetId' | '/data'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/ask-data'
    | '/_shell/beranda'
    | '/_shell/chat'
    | '/_shell/data/$datasetId'
    | '/_shell/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/ask-data': {
      id: '/_shell/ask-data'
      path: '/ask-data'
      fullPath: '/ask-data'
      preLoaderRoute: typeof ShellAskDataRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/beranda': {
      id: '/_shell/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof ShellBerandaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/data/': {
      id: '/_shell/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof ShellDataIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/data/$datasetId': {
      id: '/_shell/data/$datasetId'
      path: '/data/$datasetId'
      fullPath: '/data/$datasetId'
      preLoaderRoute: typeof ShellDataDatasetIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAskDataRoute: typeof ShellAskDataRoute
  ShellBerandaRoute: typeof ShellBerandaRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellDataDatasetIdRoute: typeof ShellDataDatasetIdRoute
  ShellDataIndexRoute: typeof ShellDataIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAskDataRoute: ShellAskDataRoute,
  ShellBerandaRoute: ShellBerandaRoute,
  ShellChatRoute: ShellChatRoute,
  ShellDataDatasetIdRoute: ShellDataDatasetIdRoute,
  ShellDataIndexRoute: ShellDataIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
